# POST http://localhost:8080/echo
# content-type: application/json

# {
#     "id" : 10,
#     "msg" : "Hello BROтеьник!"
# }

POST http://localhost:8080/login
content-type: application/json

{
    "email" : "test2@email.com",
    "password" : "testpassword2"
}


# POST http://localhost:8080/create_user
# content-type: application/json

# {
#     "email" : "test2@email.com",
#     "password" : "testpassword2"
# }