# POST http://localhost:8080/echo
# content-type: application/json

# {
#     "id" : 10,
#     "msg" : "Hello BROтеьник!"
# }

POST http://localhost:8080/login
content-type: application/json

{
    "email" : "user@email.com",
    "password" : "helloworld"
}
//123 | user@email.com | helloworld